// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://odemkncodjxdtxmkgqpr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9kZW1rbmNvZGp4ZHR4bWtncXByIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzNjYwNzIsImV4cCI6MjA2Njk0MjA3Mn0.QdqEHvRKp-eM-oJisuBjiug4ZOiFyFCEGl7sDmzuZG8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});